### ISSUE TITLE
Missing test videos

### ISSUE THREAD

**Issue by mbchang** [comphyreasoning/compositional_physics_learner#1]
On the Comphy website it looks like the link to the testing videos actually points to the testing annotations: https://drive.google.com/file/d/1qhaRGebUnwt9LdPIWvuxaBNQ-h3ahiXt/view. Would it be possible to add the testing videos to the website? Thanks!

**Comment by zfchenUnique** [comment]
Thank you for your reminder and I have updated the files accordingly!
