### ISSUE TITLE
No access to testing videos

### ISSUE THREAD

**Issue by Zest86** [comphyreasoning/compositional_physics_learner#3]
Hello,
On the ComPhy website, when I tried to access testing videos in the following link https://drive.google.com/file/d/1CerjOoLOOAt2XPeHucDdPgRbG0Se6gZN/view?usp=sharing, it is shown that I have no access to the testing videos. Could it be possible that you share the testing videos? Many thanks.

**Comment by zfchenUnique** [comment]
Hi, 
    Thanks for your interest. It seems the link has been broken. I move the testing data at https://connecthkuhk-my.sharepoint.com/:u:/g/personal/u3004417_connect_hku_hk/EQfn1U0gqNFLuwS2AAnJwkkBhzsFvxPInyQl46liJ4WaYw?e=0ygEIm
Regards
